// src/utils/aiSchema.js
// Tool definitions for Groq Tool Calling — OPTIMIZED for token savings

export const aiTools = [
  { type: "function", function: { name: "verificar_disponibilidad", description: "Stock disponible de un artículo en una fecha", parameters: { type: "object", properties: { articulo: { type: "string", description: "Nombre del artículo" }, fecha: { type: "string", description: "YYYY-MM-DD" } }, required: ["articulo"] } } },
  { type: "function", function: { name: "buscar_cliente", description: "Buscar cliente por nombre, teléfono, email o cédula", parameters: { type: "object", properties: { texto: { type: "string", description: "Texto de búsqueda" } }, required: ["texto"] } } },
  { type: "function", function: { name: "buscar_producto", description: "Buscar producto/artículo del inventario por nombre", parameters: { type: "object", properties: { nombre: { type: "string", description: "Nombre del producto" } }, required: ["nombre"] } } },
  { type: "function", function: { name: "consultar_pedidos", description: "Pedidos por fecha, rango o cliente", parameters: { type: "object", properties: { fecha: { type: "string", description: "YYYY-MM-DD" }, fecha_desde: { type: "string", description: "YYYY-MM-DD" }, fecha_hasta: { type: "string", description: "YYYY-MM-DD" }, cliente: { type: "string", description: "Nombre cliente" } } } } },
  { type: "function", function: { name: "consultar_agenda", description: "Eventos para hoy/mañana/semana/próximos días", parameters: { type: "object", properties: { periodo: { type: "string", enum: ["hoy", "manana", "semana", "proximos_7_dias", "proximos_30_dias"], description: "Período" } }, required: ["periodo"] } } },
  { type: "function", function: { name: "consultar_agenda_fecha", description: "Agenda completa de una fecha: pedidos + cotizaciones + notas", parameters: { type: "object", properties: { fecha: { type: "string", description: "YYYY-MM-DD" } }, required: ["fecha"] } } },
  { type: "function", function: { name: "resumen_financiero", description: "Ingresos, gastos y ganancia de un mes", parameters: { type: "object", properties: { mes: { type: "integer", description: "1-12" }, anio: { type: "integer", description: "Año" } } } } },
  { type: "function", function: { name: "contar_registros", description: "Contar clientes/productos/pedidos/cotizaciones/paquetes", parameters: { type: "object", properties: { tipo: { type: "string", enum: ["clientes", "productos", "pedidos", "cotizaciones", "paquetes"] } }, required: ["tipo"] } } },
  { type: "function", function: { name: "consultar_cotizaciones", description: "Cotizaciones por rango de fechas o cliente", parameters: { type: "object", properties: { fecha_desde: { type: "string", description: "YYYY-MM-DD" }, fecha_hasta: { type: "string", description: "YYYY-MM-DD" }, cliente: { type: "string", description: "Nombre cliente" } } } } },
  { type: "function", function: { name: "trazabilidad_precio", description: "Último precio de un artículo para un cliente específico", parameters: { type: "object", properties: { articulo: { type: "string", description: "Artículo" }, cliente: { type: "string", description: "Cliente" } }, required: ["articulo", "cliente"] } } },
  { type: "function", function: { name: "ultimo_cliente_articulo", description: "Último cliente que alquiló un artículo", parameters: { type: "object", properties: { articulo: { type: "string", description: "Artículo" } }, required: ["articulo"] } } },
  { type: "function", function: { name: "crear_nota", description: "Crear nota en el calendario para una fecha", parameters: { type: "object", properties: { fecha: { type: "string", description: "YYYY-MM-DD" }, descripcion: { type: "string", description: "Texto de la nota" } }, required: ["fecha", "descripcion"] } } },
  { type: "function", function: { name: "pagos_pendientes", description: "Pedidos con saldo pendiente, opcionalmente filtrar por cliente", parameters: { type: "object", properties: { cliente: { type: "string", description: "Nombre cliente (opcional)" } } } } },
  { type: "function", function: { name: "crear_cliente", description: "Crear nuevo cliente", parameters: { type: "object", properties: { nombre: { type: "string", description: "Nombre completo" }, telefono: { type: "string" }, identificacion: { type: "string" }, email: { type: "string" }, direccion: { type: "string" } }, required: ["nombre"] } } },
  { type: "function", function: { name: "actualizar_precio_producto", description: "Cambiar precio de alquiler de un producto", parameters: { type: "object", properties: { nombre: { type: "string", description: "Producto" }, nuevo_precio: { type: "number", description: "Nuevo precio en pesos" } }, required: ["nombre", "nuevo_precio"] } } },
  { type: "function", function: { name: "articulos_mas_alquilados", description: "Ranking de artículos más alquilados", parameters: { type: "object", properties: { limite: { type: "integer", description: "Top N (default 10)" } } } } },
  { type: "function", function: { name: "clientes_mas_frecuentes", description: "Ranking de mejores clientes por pedidos", parameters: { type: "object", properties: { limite: { type: "integer", description: "Top N (default 10)" } } } } },
  { type: "function", function: { name: "buscar_paquete", description: "Buscar paquetes de eventos por nombre y ver su contenido (productos incluidos, precio total). Si no se pasa nombre, lista los primeros paquetes disponibles.", parameters: { type: "object", properties: { nombre: { type: "string", description: "Nombre del paquete (opcional, vacío lista todos)" } } } } },
];